version: '3.8'

services:
  personal-blog:
    build: .
    container_name: personal-blog
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      # Add other env vars here
